### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by volkerblum** [HybriD3-database/MatD3#10]
The HybriD3 database, which is an instance of MatD3, opens with a search page that allows one to search for material, organic, inorganic etc. However, it does not (as set up in HybriD3) allow one to search for "Property". (to list, e.g., all materials for which a certain property is known)

Can this be changed and where would one make the change - in the MatD3 software or in the setup of the HybriD3 database?

Thanks!
Best wishes
Volker, Xiaochen, Svenja, Becca

**Comment by raullaasner** [comment]
The change would need to be made in the MatD3 source code, specifically in [this](https://github.com/HybriD3-database/MatD3/blob/6700447ceac9f7e3b3188438ebd4384c06e997f8/materials/views.py#L167) function. Should be an easy fix but I don't know for sure until I test it. I'll get back to you within the next few days.

**Comment by raullaasner** [comment]
Closed by e8f97653 (that commit incorrectly referred to a different issue).
