### ISSUE TITLE
API

### ISSUE THREAD

**Issue by volkerblum** [HybriD3-database/MatD3#13]
In the HybriD3 instance of MatD3, we received the following question:

the main thing we’re trying to do is get space group and atomic positions for each of the given datasets - we see this on the online instance, but we’ve been unable to get this on any of the API endpoints.

This is a good question - is it easy to see how to get particularly the space groups? Sorry I'm asking here, but the API will hopefully be further developed anyways and I didn't immediately know the answer. Thanks!

Best wishes
Volker

**Comment by aidangren** [comment]
Hi Raul - Aidan here (I'm the one who was in touch with Volker about this topic). We'd find that really helpful if we could get info on the space groups within the dataset model, and then additionally include an API endpoint for that.

Just to clarify, are the data available already or would we have to go back to each source and re-obtain the space group data? I'm happy to help if needed, since I recognize this is our request, but how long do you think this might take?

Thanks for all your help so far!

**Comment by raullaasner** [comment]
I can add the API endpoint in a few days but then the original papers would need to be revisited to store the space group information. That data was not captured at all. I don't know how long that would take - maybe several days or weeks for a grad student.

**Comment by aidangren** [comment]
Thanks for the help! It would be immensely helpful if we could add that endpoint to the API; no problem if it takes a few days as that’s fairly quick!

I’m happy to help out if I can with getting the space group data into the database, as that is really what would drive the value for us and hopefully could be helpful to other groups in the future. Is there a way I can help with that as an external person or would that need to be done by a team member?

I appreciate your help with ‘customizing’ this for us!

**Comment by volkerblum** [comment]
Thank you so much! Both Raul for the endpoint and Aidan, yes, it would be wonderful if you could help. In addition, there is also Becca Lau in our group, who we might talk to and see how we can approach this.

**Comment by aidangren** [comment]
Alright, sounds good. Do let me know how I can help; I now see the option to add data on the site, but I assume we'd want to modify existing records? Slightly complicating this is that I will be out of the office for the next few days, but I will be able to help more actively when I return. If you'd like to have a meeting to discuss next steps (and maybe we move this planning conversation off git?), I can be available. Let me know when works!

**Comment by aidangren** [comment]
Hi @raullaasner - one more question. Do you think we could add an endpoint to access the atomic positions? I know I mentioned that in conjunction with the space groups; in our lab meeting today, some of the members more experienced in this suggested that atomic positions are actually probably sufficient for what we need, as we could figure out the space groups from them. I managed to get this from the API, vs the website data:
<img width="468" alt="Screen Shot 2020-06-29 at 1 04 29 PM" src="https://user-images.githubusercontent.com/57573699/86051093-b9a08c00-ba09-11ea-988a-e786ec42d489.png">
<img width="439" alt="Screen Shot 2020-06-29 at 1 08 55 PM" src="https://user-images.githubusercontent.com/57573699/86051101-bb6a4f80-ba09-11ea-92cf-125a4752663f.png">

If I'm correct, basically, I get the coordinates but they're not affiliated with the atom that is there. Is this possible to add, as I think that's really what we're after?

**Comment by raullaasner** [comment]
I think I can create an endpoint for the atomic positions, but let me look at the code first to be sure.

I can make this and other changes on Thursday evening. Shouldn't take me more than an hour but I'm busy with work at the moment.

**Comment by volkerblum** [comment]
Thanks! Another option is that, in some form, you explain to us what needs to be done (i.e., where to start) and guide us along - either in a meeting or here at github. This could also be helpful for future instances of this kind. Is this an option?

**Comment by beccalau** [comment]
Hi all-- I'm Becca (undergrad student also working on the database). I am more than happy to help add the space groups to the published structures. I, too, think it might be beneficial to organize what needs to be done and organize a Zoom call (when you are available, of course) and see how we can revamp HybriD3.

**Comment by raullaasner** [comment]
Sorry for the silence, I was busy with other things. I added space group to the data set model and it is also part of the API now. It is just a text field at the moment. If a dropdown menu with available options would be better, let me know.

I can look at the issue about atomic positions tomorrow.

I'm fine with a Zoom call. Wednesday or Thursday would work for me.

**Comment by raullaasner** [comment]
Existing data sets can now be edited from the admin page as before. You'll notice a new field for the space group.

**Comment by raullaasner** [comment]
@aidangren I realized that there actually already is an endpoint for atomic coordinates: `/materials/get-atomic-coordinates/<pk>`, where `<pk>` is a subset id (primary key), which you can find as part of the data set response. For instance, make a REST request to `https://materials.hybrid3.duke.edu/materials/datasets/217/`. You will find a subset with the id 271. Then make a request for `https://materials.hybrid3.duke.edu/materials/get-atomic-coordinates/271` and you will see the atomic positions along with atom labels. Let me know if this needs clarification or could be improved on somehow. Closing for now.
