### ISSUE TITLE
Documentation should provide citable reference and the link to it

### ISSUE THREAD

**Issue by volkerblum** [HybriD3-database/MatD3#16]
Hi Raul,
I noticed today that this page:

https://hybrid3-database.readthedocs.io/en/latest/

does not provide the JOSS paper as the reference to cite and to link to.

Could you add this to the documentation? (err ... I just tried but did not immediately succeed ... I'm sorry about this)

Thank you!
Best wishes
Volker

**Comment by raullaasner** [comment]
Hi Volker,
I pushed the fix. Let me know if the wording needs to be adjusted!
