### ISSUE TITLE
GitHub License Recognition

### ISSUE THREAD

**Issue by dgasmith** [HybriD3-database/MatD3#5]
I am unsure why, but GitHub isn't picking up that the license is BSD-2C. This recognization is often important so that users can get a quick feel for the repository. You may want to run [licensee](https://licensee.github.io/licensee/) which GitHub uses or consider rerendering the license via GitHub mechanisms.

**Comment by raullaasner** [comment]
I reformatted the license to coincide exactly with the GitHub BSD-2C template.
